### ISSUE TITLE
Production chain

### ISSUE THREAD

**Issue by MrBSmith** [MrBSmith/XionLeak#695]
- Must be modulable in any shape the user want ba adding/removing points (And change shape accordingly when this happens)

- Is composed of a Belt: the moving part, where are attached Hooks, that can be moved around on the belt in the editor

- Hooks can grab interactive objects be passing on them; players have to use the action key to be grabbed

**Comment by Weact** [comment]
- [ ] Production Chain

- [ ] Element Moving Along the Chain

- [ ] Grab Interaction
